//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MockApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  
        ///  &quot;Expression&quot;: null,
        ///  &quot;CurrentField&quot;: null,
        ///  &quot;ID&quot;: &quot;42b3a65b-ee2b-414e-b2b6-65b1b2a634a6&quot;,
        ///  &quot;Version&quot;: 0.0,
        ///  &quot;Status&quot;: null,
        ///  &quot;VersionStatus&quot;: null,
        ///  &quot;Text&quot;: null,
        ///  &quot;ProjectID&quot;: null,
        ///  &quot;Name&quot;: &quot;Huru Project&quot;,
        ///  &quot;Fields&quot;: [
        ///    {
        ///      &quot;CurrentField&quot;: null,
        ///      &quot;FormID&quot;: null,
        ///      &quot;SectionID&quot;: null,
        ///      &quot;Precondition&quot;: null,
        ///      &quot;PostCondition&quot;: null,
        ///      &quot;Expression&quot;: null,
        ///      &quot;ShowInDashBoard&quot;: false,
        ///      &quot;FieldID&quot;: null,
        ///      &quot;Status&quot;: null,
        ///      &quot;Text&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HuruDef {
            get {
                return ResourceManager.GetString("HuruDef", resourceCulture);
            }
        }
    }
}
