//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileDataKit_Collect.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileDataKit_Collect.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Version&quot;:0.0,&quot;Status&quot;:null,&quot;VersionStatus&quot;:null,&quot;Text&quot;:null,&quot;Name&quot;:&quot;M Vaccination&quot;,&quot;Fields&quot;:[{&quot;FormID&quot;:null,&quot;SectionID&quot;:null,&quot;DependOn&quot;:null,&quot;ShowInDashBoard&quot;:false,&quot;FieldID&quot;:null,&quot;Status&quot;:null,&quot;Text&quot;:&quot;Preliminary Information&quot;,&quot;ControlType&quot;:&quot;Section&quot;,&quot;Name&quot;:&quot;edc26477-c807-44e3-ab8a-144ddeb8e820&quot;,&quot;Required&quot;:false,&quot;No&quot;:1,&quot;Fields&quot;:[{&quot;FormID&quot;:null,&quot;SectionID&quot;:null,&quot;DependOn&quot;:null,&quot;ShowInDashBoard&quot;:false,&quot;FieldID&quot;:null,&quot;Status&quot;:null,&quot;Text&quot;:&quot;Facility Name &quot;,&quot;ControlType&quot;:null,&quot;Name&quot;:&quot;Q1&quot;,&quot;Required&quot;:false,&quot;No&quot;:0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
